backend: 
  name: git-gateway 
  branch: master # 分支名称，按你的实际情况而定  
media_folder: "docs/.vuepress/public/uploads" # 媒体文件夹路径 
public_folder: "/uploads"  

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}